# Generated by Django 3.1.3 on 2022-06-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Michi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.TextField()),
                ('color', models.TextField()),
                ('origen', models.TextField()),
                ('historia', models.TextField()),
                ('rareza', models.TextField()),
            ],
        ),
    ]
